"""two-factor authentication

Revision ID: 23e9d8ca48c2
Revises: 834b1a697901
Create Date: 2023-03-04 14:26:06.269415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e9d8ca48c2'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_phone', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_phone')
    # ### end Alembic commands ###
